---
title: "Data generation and model"
format: pdf
editor: visual
---

## Import des bilbiothèques

```{r, echo:false}
library(rockchalk)
library(dplyr)
library(this.path)
library(lme4)
library(lcmm)
```

## Import des résultats

```{r, echo: false}
MAE_train <- read.csv2(file = paste(this.dir(), "/Résultats R script/MAE train.csv", sep = ""), sep=',')
MAE_test <- read.csv2(file = paste(this.dir(), "/Résultats R script/MAE test.csv", sep = ""), sep=',')
MSE_train <- read.csv2(file = paste(this.dir(), "/Résultats R script/MSE train.csv", sep = ""), sep=',')
MSE_test <- read.csv2(file = paste(this.dir(), "/Résultats R script/MsE train.csv", sep = ""), sep = ',')
Valeurs_Biais <- read.csv2(file = paste(this.dir(), "/Résultats R script/Valeurs et Biais.csv", sep = ""), sep = ',')
```

```{r, echo:false}
val_moy <- colMeans(as.numeric(Valeurs_Biais[c('µ.Gamma1','µ.Gamma2','µ.Gamma3','sigma.Gamma1','sigma.Gamma2','sigma.Gamma3')]))
val_moy
```
```{r}
biais_moy <-colMeans(as.numeric(Valeurs_Biais[c('Biais.µ.Gamma1','Biais.µ.Gamma2','Biais.µ.Gamma3','Biais.sigma.Gamma1','Biais.sigma.Gamma2','Biais.sigma.Gamma3')]))
biais_moy
```

```{r, echo:false}
perf_moy <- data.frame('MAE_train' = mean(as.numeric(MAE_train$MAE_train)), 
                       'MSE_train' = mean(as.numeric(MSE_train$MSE_train)),
                       'MAE_test' = mean(as.numeric(MAE_test$MAE_train)), 
                       'MSE_test' = mean(as.numeric(MSE_test$X.MSE_train))
                       )
perf_moy
```

```{r}

```

